version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    versioning-strategy: increase
    commit-message:
      prefix: "[npm]"
    groups:
       dependencies:
          patterns:
            - "*"
