export const CONFIG = {
  II_ENV: import.meta.env.VITE_II_ENV,
  II_CANISTER_ID: import.meta.env.VITE_II_CANISTER_ID,
  MP_CANISTER_ID: import.meta.env.VITE_MP_CANISTER_ID,
  AWS_VERIFY_PHONENUMBER: import.meta.env.VITE_AWS_VERIFY_PHONENUMBER_DOMAIN,
  ENCRYPTION_SECRET: import.meta.env.VITE_ENCRYPTION_SECRET,
  API: {
    CREATE_ACCOUNT: import.meta.env.VITE_API_CREATE_ACCOUNT,
    CREATE_PERSONA: import.meta.env.VITE_API_CREATE_PERSONA,
  },
}
