declare const RARIBLE_X_API_KEY: string
declare const PROD_RARIBLE_X_API_KEY: string
declare const GOERLI_ALCHEMY_API_KEY: string
declare const ETH_ALCHEMY_API_KEY: string
declare const MATIC_ALCHEMY_API_KEY: string
declare const MUMBAI_ALCHEMY_API_KEY: string
declare const AWS_EXCHANGE_RATE: string
declare const AWS_ECDSA_REGISTER: string
declare const AWS_ECDSA_REGISTER_ADDRESS: string
declare const AWS_ECDSA_GET_ANONYMOUS: string
declare const AWS_EXECUTE_CANDID: string
declare const AWS_ECDSA_SIGN: string
declare const AWS_PASSKEY: string
declare const AWS_SIGNATURE_EVENT: string
declare const AWS_SYMMETRIC: string
declare const BITCOIN_WALLET_CANISTER_ID: string
declare const BTC_SIGNER_CANISTER_ID: string
declare const IC_SIGNER_CANISTER_ID: string
declare const CHAIN_NETWORK: string
declare const VAULTS_ORIGIN: string
declare const BLOCK_CYPHER_TOKEN: string
declare const CYCLES_MINTER_CANISTER_ID: string
declare const ECDSA_SIGNER_CANISTER_ID: string
declare const ETH_SECRET_STORAGE_CANISTER_ID: string
declare const FRONTEND_MODE: string
declare const GOOGLE_CLIENT_ID: string
declare const IC_HOST: string
declare const IDENTITY_MANAGER_CANISTER_ID: string
declare const II_ENV: string
declare const INTERNET_IDENTITY_CANISTER_ID: string
declare const IS_DEV: string
declare const IS_E2E_TEST: string
declare const LEDGER_CANISTER_ID: string
declare const METAMASK_SIGNIN_MESSAGE: string
declare const NFID_PROVIDER_URL: string
declare const PUB_SUB_CHANNEL_CANISTER_ID: string
declare const RAMP_WALLET_API_KEY: string
declare const RAMP_WALLET_SDK_URL: string
declare const SENTRY_RELEASE: string
declare const SIGNIN_GOOGLE: string
declare const AWS_SIGNIN_GOOGLE_V2: string
declare const USERGEEK_API_KEY: string
declare const VAULT_CANISTER_ID: string
declare const VERIFIER_CANISTER_ID: string
declare const VERIFY_PHONE_NUMBER: string
declare const WALLET_CONNECT_PROJECT_ID: string
declare const AWS_SEND_VERIFICATION_EMAIL: string
declare const AWS_LINK_GOOGLE_ACCOUNT: string
declare const AWS_CHECK_VERIFICATION: string
declare const AWS_VERIFY_EMAIL: string
declare const AWS_FETCH_ALTERNATIVE_ORIGINS: string
