declare const AWS_EXCHANGE_RATE: string
declare const AWS_X_TWEET: string
declare const AWS_ECDSA_REGISTER: string
declare const AWS_ECDSA_REGISTER_ADDRESS: string
declare const AWS_ECDSA_GET_ANONYMOUS: string
declare const AWS_EXECUTE_CANDID: string
declare const AWS_ECDSA_SIGN: string
declare const AWS_PASSKEY: string
declare const AWS_SIGNATURE_EVENT: string
declare const AWS_PUBLIC_KEY: string
declare const AWS_SYMMETRIC: string
declare const IC_SIGNER_CANISTER_ID: string
declare const CHAIN_NETWORK: string
declare const CYCLES_MINTER_CANISTER_ID: string
declare const ECDSA_SIGNER_CANISTER_ID: string
declare const SWAP_TRS_STORAGE: string
declare const NFID_WALLET_CANISTER: string
declare const FRONTEND_MODE: string
declare const ENV: string
declare const GOOGLE_CLIENT_ID: string
declare const IC_HOST: string
declare const IDENTITY_MANAGER_CANISTER_ID: string
declare const II_MODE: string
declare const INTERNET_IDENTITY_CANISTER_ID: string
declare const IS_DEV: string
declare const IS_E2E_TEST: string
declare const LEDGER_CANISTER_ID: string
declare const ICRC1_REGISTRY_CANISTER_ID: string
declare const ICRC1_ORACLE_CANISTER_ID: string
declare const DELEGATION_FACTORY: string
declare const PASSKEY_STORAGE: string
declare const NFID_PROVIDER_URL: string
declare const PUB_SUB_CHANNEL_CANISTER_ID: string
declare const SDK_GIT_HASH: string
declare const SIGNIN_GOOGLE: string
declare const AWS_SIGNIN_GOOGLE_V2: string
declare const USERGEEK_API_KEY: string
declare const VAULT_CANISTER_ID: string
declare const VERIFIER_CANISTER_ID: string
declare const VERIFY_PHONE_NUMBER: string
declare const AWS_SEND_VERIFICATION_EMAIL: string
declare const AWS_LINK_GOOGLE_ACCOUNT: string
declare const AWS_CHECK_VERIFICATION: string
declare const AWS_VERIFY_EMAIL: string
declare const CANISTER_WITH_AT_LEAST_ONE_PASSKEY: string
declare const PATRON_CANISTER_ID: string
declare const CHAIN_FUSION_SIGNER_CANISTER_ID: string