export const mockAttributesResponse = [
  [
    [
      0,
      "Attribute",
      [
        [0, "Cd Drive"],
        [1, "Dirty"],
        [2, "None"],
        [3, "Slots"],
        [4, "Vent"],
      ],
    ],
    [
      1,
      "Clothes",
      [
        [0, "Blazer Beige"],
        [1, "Blazer Black"],
        [2, "Blazer Blood Red"],
        [3, "Blazer Blue"],
        [4, "Blazer Brown"],
        [5, "Blazer Gray"],
        [6, "Blazer Green"],
        [7, "Blazer Hype"],
        [8, "Blazer Orange"],
        [9, "Blazer Pink"],
        [10, "Blazer Purple"],
        [11, "Blazer Red"],
        [12, "Blazer White"],
        [13, "Blazer Yellow"],
        [14, "Business 1"],
        [15, "Business 2"],
        [16, "Business 3"],
        [17, "Hawaiian 1"],
        [18, "Hawaiian 2"],
        [19, "Hawaiian 3"],
        [20, "Hawaiian 4"],
        [21, "Hawaiian 5"],
        [22, "Hitman"],
        [23, "Hoodie Beige"],
        [24, "Hoodie Black"],
        [25, "Hoodie Blue"],
        [26, "Hoodie Brown"],
        [27, "Hoodie Checkered 1"],
        [28, "Hoodie Checkered 2"],
        [29, "Hoodie Purple"],
        [30, "Hoodie Rainbow"],
        [31, "Hoodie Red"],
        [32, "Hoodie White"],
        [33, "Inmate"],
        [34, "Nude"],
        [35, "Pirate 1"],
        [36, "Pirate 2"],
        [37, "Preppy"],
        [38, "Robe Regal Purple"],
        [39, "Robe Regal Red"],
        [40, "Royal Robe"],
        [41, "Royal Robe 2"],
        [42, "Sailor Uniform"],
        [43, "Santa Suit"],
        [44, "Scrubs"],
        [45, "Smooth"],
        [46, "Tee Beige"],
        [47, "Tee Black"],
        [48, "Tee Blood Red"],
        [49, "Tee Blue"],
        [50, "Tee Brown"],
        [51, "Tee Gray"],
        [52, "Tee Green"],
        [53, "Tee Heart"],
        [54, "Tee Hype"],
        [55, "Tee Orange"],
        [56, "Tee Pink"],
        [57, "Tee Purple"],
        [58, "Tee Red"],
        [59, "Tee White"],
        [60, "Tee Yellow"],
        [61, "Turtleneck Beige"],
        [62, "Turtleneck Black"],
        [63, "Turtleneck Brown"],
        [64, "Turtleneck Ugly"],
        [65, "Turtleneck White"],
        [66, "Vest Beige"],
        [67, "Vest Black"],
        [68, "Vest Brown"],
        [69, "Vest Camo"],
        [70, "Vest White"],
      ],
    ],
    [
      2,
      "Hat",
      [
        [0, "Antenna"],
        [1, "Arrgghhh"],
        [2, "Arrgghhh 2"],
        [3, "Beanie Beige"],
        [4, "Beanie Black"],
        [5, "Beanie Blue"],
        [6, "Beanie Brown"],
        [7, "Beanie Green"],
        [8, "Beanie Red"],
        [9, "Beanie White"],
        [10, "Beehive"],
        [11, "Boot"],
        [12, "Bow"],
        [13, "Cap Beige"],
        [14, "Cap Black"],
        [15, "Cap Blue"],
        [16, "Cap Brown"],
        [17, "Cap Dfinity"],
        [18, "Cap Green"],
        [19, "Cap Red"],
        [20, "Cap White"],
        [21, "Chef Hat"],
        [22, "Cowboy Hat"],
        [23, "Crown"],
        [24, "Diamond Crown"],
        [25, "Dice"],
        [26, "Energy Dome"],
        [27, "Fedora"],
        [28, "Fez"],
        [29, "Fish Tank"],
        [30, "Floating Brain"],
        [31, "Halo"],
        [32, "Headband Black"],
        [33, "Headband Blue"],
        [34, "Headband Red"],
        [35, "Headband White"],
        [36, "Ice Cream Cone"],
        [37, "Inmate Cap"],
        [38, "Mohawk Green"],
        [39, "Mohawk Primary"],
        [40, "Mohawk Purple"],
        [41, "Mohawk Red"],
        [42, "Mortarboard"],
        [43, "Ninja"],
        [44, "None"],
        [45, "Pancakes"],
        [46, "Plant"],
        [47, "Plunger"],
        [48, "Police Cap"],
        [49, "Present"],
        [50, "Santa Cap"],
        [51, "Scrub Cap"],
        [52, "Skullcap Black"],
        [53, "Skullcap Blue"],
        [54, "Skullcap Red"],
        [55, "Skullcap White"],
        [56, "Sombrero"],
        [57, "Sonar"],
        [58, "Spilled Noodles"],
        [59, "Straw Hat"],
        [60, "Sword"],
        [61, "Top Hat Black"],
        [62, "Top Hat Red"],
        [63, "Top Hat White"],
        [64, "Viking Helm"],
        [65, "Viking Helm 2"],
        [66, "Wizard"],
      ],
    ],
    [
      3,
      "Monitor",
      [
        [0, "Beige"],
        [1, "Black"],
        [2, "Blood Red"],
        [3, "Blue"],
        [4, "Brown"],
        [5, "Chrome"],
        [6, "Gray"],
        [7, "Green"],
        [8, "Orange"],
        [9, "Pink"],
        [10, "Purple"],
        [11, "Red"],
        [12, "Rust"],
        [13, "Stone"],
        [14, "White"],
        [15, "Yellow"],
      ],
    ],
    [
      4,
      "Screen",
      [
        [0, "404"],
        [1, "Alert"],
        [2, "Angry"],
        [3, "Angy"],
        [4, "Bsod"],
        [5, "Bitcoin"],
        [6, "Blank"],
        [7, "Bliss"],
        [8, "Bloody"],
        [9, "Cheeky"],
        [10, "Cool"],
        [11, "Dfinity"],
        [12, "Doggy"],
        [13, "Dreaming"],
        [14, "Dump"],
        [15, "Eliminate"],
        [16, "Empty Head"],
        [17, "Hahaha"],
        [18, "Happy"],
        [19, "Hills"],
        [20, "Infinity"],
        [21, "Kos"],
        [22, "Meh"],
        [23, "Mona"],
        [24, "Motoko"],
        [25, "Npc"],
        [26, "Not Amused"],
        [27, "Not Pleased"],
        [28, "Pong"],
        [29, "Pump"],
        [30, "Puppy Eyes"],
        [31, "Pure Evil"],
        [32, "Rectangles"],
        [33, "Skull"],
        [34, "Stand By"],
        [35, "Staring"],
        [36, "Static"],
        [37, "Target"],
        [38, "Tired"],
        [39, "Tot"],
        [40, "X"],
        [41, "Amaze"],
        [42, "Cmd 1"],
        [43, "Cmd 2"],
        [44, "Gm"],
        [45, "Ii"],
        [46, "Moe"],
      ],
    ],
    [
      5,
      "Sides",
      [
        [0, "9001"],
        [1, "Arrow"],
        [2, "Cupid"],
        [3, "Demon Horns"],
        [4, "Devil Horns"],
        [5, "None"],
        [6, "Sword"],
      ],
    ],
  ],
  [
    [
      0,
      [
        [3, 15],
        [4, 26],
        [0, 2],
        [1, 55],
        [2, 38],
        [5, 1],
      ],
    ],
    [
      1,
      [
        [3, 6],
        [4, 23],
        [0, 2],
        [1, 7],
        [2, 62],
        [5, 5],
      ],
    ],
    [
      4232,
      [
        [3, 13],
        [4, 45],
        [0, 2],
        [1, 13],
        [2, 64],
        [5, 5],
      ],
    ],
    [
      4233,
      [
        [3, 1],
        [4, 39],
        [0, 2],
        [1, 58],
        [2, 4],
        [5, 5],
      ],
    ],
    [
      4234,
      [
        [3, 14],
        [4, 45],
        [0, 2],
        [1, 52],
        [2, 55],
        [5, 5],
      ],
    ],
    [
      4235,
      [
        [3, 14],
        [4, 43],
        [0, 4],
        [1, 35],
        [2, 61],
        [5, 5],
      ],
    ],
    [
      4236,
      [
        [3, 3],
        [4, 18],
        [0, 2],
        [1, 17],
        [2, 59],
        [5, 5],
      ],
    ],
  ],
]

export const expectedAttributesResponse = {
  mappedValues: [
    { category: "Monitor", option: "Black" },
    { category: "Screen", option: "Tot" },
    { category: "Attribute", option: "None" },
    { category: "Clothes", option: "Tee Red" },
    { category: "Hat", option: "Beanie Black" },
    { category: "Sides", option: "None" },
  ],
}
