declare const AWS_SYMMETRIC: string
declare const CURRCONV_TOKEN: string
declare const CYCLES_MINTER_CANISTER_ID: string
declare const ECDSA_SIGNER_CANISTER_ID: string
declare const ETH_SECRET_STORAGE_CANISTER_ID: string
declare const FRONTEND_MODE: string
declare const GOOGLE_CLIENT_ID: string
declare const IDENTITY_MANAGER_CANISTER_ID: string
declare const INTERNET_IDENTITY_CANISTER_ID: string
declare const IS_E2E_TEST: string
declare const LEDGER_CANISTER_ID: string
declare const METAMASK_SIGNIN_MESSAGE: string
declare const NFID_PROVIDER_URL: string
declare const PUB_SUB_CHANNEL_CANISTER_ID: string
declare const RAMP_WALLET_API_KEY: string
declare const RAMP_WALLET_SDK_URL: string
declare const SENTRY_RELEASE: string
declare const SIGNIN_GOOGLE: string
declare const USERGEEK_API_KEY: string
declare const VAULT_CANISTER_ID: string
declare const VERIFIER_CANISTER_ID: string
declare const VERIFY_PHONE_NUMBER: string
declare const WALLET_CONNECT_PROJECT_ID: string
declare const AWS_AUTH_STATS: string
declare const AWS_SIGNATURE_EVENT: string
