#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

if ! echo "$commit_msg" | grep -qE '\[sc-\d+\]$'; then
  echo "❌ Commit message must end with '[sc-{ticketNumber}]'."
  exit 1
fi

yarn commitlint --edit "$1"
