# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Desktop Tests CI

on:
  pull_request:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to run against"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - ic
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      docker_rebuild:
        description: "Rebuild Docker image"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
      test_cycle:
        description: "Test Cycle"
        required: true
        default: "no_google"
        type: choice
        options:
          - "full"
          - "no-google"

env:
  CI_DEBUG: "true"

jobs:
  check-secrets:
    name: Check secrets
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - name: Checkout CI repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: internet-identity-labs/ci_libs
          ref: main
          path: ci_libs

      - name: Show concurency group
        run: |
          echo "REF: ${{ github.ref }}"
          echo "HEAD_REF: ${{ github.head_ref }}"
          echo "BASE_REF: ${{ github.base_ref }}"
          echo "EVENT_NAME: ${{ github.event_name }}"
          echo "REF_NAME: ${{ github.ref_name }}"
          echo "group: nfid-frontend-tests-docker-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.ref_name, 'main' ) }}-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.event_name, 'push' ) || github.ref_name }}"
          echo "group: nfid-frontend-tests-e2e-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.ref_name, 'main' ) }}-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.event_name, 'push' ) || github.ref_name }}"
          echo "cancel-in-progress: ${{ contains( github.event.inputs.test_cycle, 'no-google' ) || contains( github.event_name, 'pull_request' ) }}"

      - name: Check secrets
        run: |
          source ${{ github.workspace }}/ci_libs/CI_LIBS.sh
          JSON='${{ toJSON(env) }}'
          ci_check_secrets "${JSON}"
        env:
          URL_AWS_USER_E2E_GOOGLE: ${{secrets.URL_AWS_USER_E2E_GOOGLE}}
          LAMBDA_IDENTITY: ${{secrets.LAMBDA_IDENTITY}}
          USERGEEK_API_KEY: ${{secrets.PROD_USERGEEK_API_KEY}}
          USER_DATA_DIR: ${{secrets.USER_DATA_DIR}}
          GH_NPM_REGISTRY: ${{secrets.PSYCHEDELIC_GH_NPM_REGISTRY}}
          NFID_FRONTEND_E2E_REPORT_AWS_ACCESS_KEY_ID: ${{secrets.NFID_FRONTEND_E2E_REPORT_AWS_ACCESS_KEY_ID}}
          NFID_FRONTEND_E2E_REPORT_AWS_SECRET_ACCESS_KEY: ${{secrets.NFID_FRONTEND_E2E_REPORT_AWS_SECRET_ACCESS_KEY}}

  docker-for-e2e:
    name: Docker Image Build
    needs: check-secrets
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: nfid-test

    concurrency:
      group: nfid-frontend-tests-docker-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.ref_name, 'main' ) }}-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.event_name, 'push' ) || github.ref_name }}
      cancel-in-progress: ${{ contains( github.event.inputs.test_cycle, 'no-google' ) || contains( github.event_name, 'pull_request' ) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout CI repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: internet-identity-labs/ci_libs
          ref: main
          path: ci_libs

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Pull Build Push Image
        run: |
          source ${{ github.workspace }}/ci_libs/CI_LIBS.sh

          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo ${IMAGE_ID} | tr '[A-Z]' '[a-z]')

          # Check is this pull request
          if [ -z "${{ github.head_ref }}" ]; then
            # If NOT
            # Strip git ref prefix from version
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          else
            # If YES
            # Strip git ref prefix from version and left pull-request number
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\([0-9]\+\)/\(.*\),\1-\2,')
          fi

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo ${VERSION} | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "${VERSION}" == "main" ] && VERSION=latest

          ci_echo_info "IMAGE_ID: ${IMAGE_ID}" >&2
          ci_echo_info "VERSION : ${VERSION}" >&2

          ci_echo_debug "DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect ${IMAGE_ID}:${VERSION} >/dev/null" >&2
          if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect ${IMAGE_ID}:${VERSION} >/dev/null; then
            ci_echo_info "Docker image '${IMAGE_ID}:${VERSION}' was found" >&2
            DOCKER_REBUILD="false"
          else
            ci_echo_warn "Image '${IMAGE_ID}:${VERSION}' was not found" >&2
            DOCKER_REBUILD="true"
          fi

          if [ "${DOCKER_REBUILD}" == "true" ] || [ "${{ github.event.inputs.docker_rebuild }}" == "true" ]; then
            ci_echo_warn "Will try to build the Docker Image." >&2

            pushd ./docker-e2e-tests

            ci_echo_debug "docker build . \
              --build-arg USER_ID=$(id -u) \
              --build-arg GROUP_ID=$(id -g) \
              --file Dockerfile \
              --tag ${IMAGE_NAME} \
              --label 'runnumber=${GITHUB_RUN_ID}'" >&2

            docker build . \
              --build-arg USER_ID=$(id -u) \
              --build-arg GROUP_ID=$(id -g) \
              --file Dockerfile \
              --tag ${IMAGE_NAME} \
              --label "runnumber=${GITHUB_RUN_ID}"

            ci_echo_debug "docker tag ${IMAGE_NAME} ${IMAGE_ID}:${VERSION}" >&2
            docker tag ${IMAGE_NAME} ${IMAGE_ID}:${VERSION}

            ci_echo_debug "docker push ${IMAGE_ID}:${VERSION}" >&2
            docker push ${IMAGE_ID}:${VERSION}
          fi

  unit-tests:
    name: Unit Tests
    needs: check-secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout CI repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: internet-identity-labs/ci_libs
          ref: main
          path: ci_libs

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Versions
        run: |
          source ${{ github.workspace }}/ci_libs/CI_LIBS.sh

          ci_versions

      - name: Build project
        run: |
          source ${{ github.workspace }}/ci_libs/CI_LIBS.sh
          cat > ~/.npmrc << EOF
          @psychedelic:registry=https://npm.pkg.github.com
          @internet-identity-labs:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${GH_NPM_REGISTRY}
          EOF

          ci_echo_debug "yarn --prefer-offline" >&2
          yarn --prefer-offline --frozen-lockfile

        env:
          GH_NPM_REGISTRY: ${{secrets.PSYCHEDELIC_GH_NPM_REGISTRY}}
          LAMBDA_IDENTITY: ${{secrets.LAMBDA_IDENTITY}}

      - name: Run unit tests
        run: |
          source ${{ github.workspace }}/ci_libs/CI_LIBS.sh

          ci_echo_debug "npx env-cmd -f .env.test nx run-many --target=test --skip-nx-cache" >&2
          npx env-cmd -f .env.test nx run-many --target=test --skip-nx-cache
        env:
          LAMBDA_IDENTITY: ${{secrets.LAMBDA_IDENTITY}}

      - name: Upload build artefacts
        uses: actions/upload-artifact@v4
        if: ${{ ! cancelled() }}
        with:
          name: yarn-error-logs
          path: /home/runner/work/nfid-frontend/nfid-frontend/yarn-error.log

  e2e-tests:
    name: E2E Tests
    needs: docker-for-e2e
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: nfid-test
    concurrency:
      group: nfid-frontend-tests-e2e-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.ref_name, 'main' ) }}-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.event_name, 'push' ) || github.ref_name }}
      cancel-in-progress: ${{ contains( github.event.inputs.test_cycle, 'no-google' ) || contains( github.event_name, 'pull_request' ) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout CI repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: internet-identity-labs/ci_libs
          ref: main
          path: ci_libs

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Pull Image and preparing Env Vars
        id: pull_image
        run: |
          source ${{ github.workspace }}/ci_libs/CI_LIBS.sh

          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo ${IMAGE_ID} | tr '[A-Z]' '[a-z]')

          # Check is this pull request
          if [ -z "${{ github.head_ref }}" ]; then
            # If NOT
            # Strip git ref prefix from version
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          else
            # If YES
            # Strip git ref prefix from version and left pull-request number
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\([0-9]\+\)/\(.*\),\1-\2,')
          fi

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo ${VERSION} | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "${VERSION}" == "main" ] && VERSION=latest

          ci_echo_info "IMAGE_ID: ${IMAGE_ID}" >&2
          ci_echo_info "VERSION : ${VERSION}" >&2

          ci_echo_debug "docker pull ${IMAGE_ID}:${VERSION}" >&2
          docker pull ${IMAGE_ID}:${VERSION}

          # Save VARS for next steps
          case "${{ github.event.inputs.test_cycle }}" in
            full)
              TEST_ADD_PARAMS=""
              ;;
            *)
              TEST_ADD_PARAMS="--cucumberOpts.tagExpression='not @only_deploy_to_main and not @pending and not @mobile'"
              ;;
          esac

          # If branch main, run full cycle
          if [ "${{ github.ref_name }}" == 'main' ]; then
            TEST_ADD_PARAMS=""
          fi

          echo "IMAGE_ID=${IMAGE_ID}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "CI_DEBUG=${CI_DEBUG}" >> $GITHUB_ENV
          echo "TEST_ADD_PARAMS="${TEST_ADD_PARAMS}"" >> $GITHUB_ENV

      - name: Checkout Google user E2E
        uses: actions/checkout@v4
        with:
          repository: internet-identity-labs/user-google-e2e
          path: apps/nfid-frontend-e2e/chrome-user-data-dir
          ref: main
          token: ${{ secrets.PAT }}

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/.eslintcache
          key: test-nfid-fe

      - name: Run tests
        run: |
          source ${{ github.workspace }}/ci_libs/CI_LIBS.sh

          ci_echo_info "Cleaning Allure folders" >&2
          rm -rf apps/nfid-frontend-e2e/allure-results
          rm -rf apps/nfid-frontend-e2e/allure-report
          mkdir -p apps/nfid-frontend-e2e/allure-results
          mkdir -p apps/nfid-frontend-e2e/allure-report

          cat > npmrc_file << EOF
          @psychedelic:registry=https://npm.pkg.github.com
          @internet-identity-labs:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${GH_NPM_REGISTRY}
          EOF

          cat > docker_env << EOF
            IS_DEV=true
            IS_E2E_TEST=true
            USERGEEK_API_KEY=${USERGEEK_API_KEY}
            GH_NPM_REGISTRY=${GH_NPM_REGISTRY}

            URL_AWS_USER_E2E_GOOGLE=${URL_AWS_USER_E2E_GOOGLE}
            LAMBDA_IDENTITY=${LAMBDA_IDENTITY}
          EOF

          ci_echo_debug "docker run --rm \
            -v $(pwd):/home/user/workdir \
            -v $(pwd)/npmrc_file:/home/user/.npmrc \
            --env-file $(pwd)/docker_env \
            -e CI_DEBUG='${CI_DEBUG}' \
            ${IMAGE_ID}:${VERSION} \
            '${TEST_ADD_PARAMS}'" >&2

          docker run --rm \
            -v $(pwd):/home/user/workdir \
            -v $(pwd)/npmrc_file:/home/user/.npmrc \
            --env-file $(pwd)/docker_env \
            -e CI_DEBUG="${CI_DEBUG}" \
            ${IMAGE_ID}:${VERSION} \
            "${TEST_ADD_PARAMS}"
        env:
          IS_DEV: true
          IS_E2E_TEST: true
          USERGEEK_API_KEY: ${{secrets.PROD_USERGEEK_API_KEY}}
          GH_NPM_REGISTRY: ${{secrets.PSYCHEDELIC_GH_NPM_REGISTRY}}
          URL_AWS_USER_E2E_GOOGLE: ${{secrets.URL_AWS_USER_E2E_GOOGLE}}
          LAMBDA_IDENTITY: ${{secrets.LAMBDA_IDENTITY}}

      - name: Save test results
        if: ${{ ! cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          path: apps/nfid-frontend-e2e/allure-results
          name: allure-results-${{github.RUN_ID}}${{github.RUN_ATTEMPT}}

      - name: Upload Chrome logs
        uses: actions/upload-artifact@v4
        if: ${{ ! cancelled() }}
        with:
          retention-days: 1
          name: chrome_debug.log
          path: apps/nfid-frontend-e2e/chrome-user-data-dir/chrome_debug.log

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: ${{ ! cancelled() }}
        with:
          retention-days: 1
          name: dist
          path: dist

  allure-report:
    name: Allure Reports
    needs: e2e-tests
    if: ${{ ! cancelled() }}
    runs-on: ubuntu-latest
    env:
      URL: ${{ github.event.pull_request.comments_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_URL: http://nfid-frontend-e2e-report.s3-website-us-east-1.amazonaws.com/${{github.RUN_ID}}${{github.RUN_ATTEMPT}}/index.html
      NFID_FRONTEND_E2E_REPORT_AWS_ACCESS_KEY_ID: ${{secrets.NFID_FRONTEND_E2E_REPORT_AWS_ACCESS_KEY_ID}}
      NFID_FRONTEND_E2E_REPORT_AWS_SECRET_ACCESS_KEY: ${{secrets.NFID_FRONTEND_E2E_REPORT_AWS_SECRET_ACCESS_KEY}}
    steps:
      - name: Download report history from S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://nfid-frontend-e2e-report/last-history
          destination: gh-pages/last-history
          aws_access_key_id: ${{ secrets.NFID_FRONTEND_E2E_REPORT_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.NFID_FRONTEND_E2E_REPORT_AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          flags: --recursive

      - name: Load test results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-${{github.RUN_ID}}${{github.RUN_ATTEMPT}}
          path: apps/nfid-frontend-e2e/allure-results

      - name: Preparing the report
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: apps/nfid-frontend-e2e/allure-results
          gh_pages: gh-pages
          allure_report: apps/nfid-frontend-e2e/allure-report
          allure_history: apps/nfid-frontend-e2e/allure-history
          github_run_num: ${{github.RUN_ID}}${{github.RUN_ATTEMPT}}

      - name: Upload report to S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: apps/nfid-frontend-e2e/allure-history
          destination: s3://nfid-frontend-e2e-report
          aws_access_key_id: ${{ secrets.NFID_FRONTEND_E2E_REPORT_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.NFID_FRONTEND_E2E_REPORT_AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          flags: --recursive

      - name: Upload url to PR comments
        env:
          target_url: http://nfid-frontend-e2e-report.s3-website-us-east-1.amazonaws.com/${{github.RUN_ID}}${{github.RUN_ATTEMPT}}/index.html
        run: |
          echo $TARGET_URL
          if [ -n "${URL}" ]; then
            printf -v data '{ "body": "%s" }' "$TARGET_URL" &&
            curl \
              -X POST \
              $URL \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "$data"
          fi

      - name: Upload url to file
        env:
          target_url: http://nfid-frontend-e2e-report.s3-website-us-east-1.amazonaws.com/${{github.RUN_ID}}${{github.RUN_ATTEMPT}}/index.html
        run: echo "$target_url" > "report_url.txt"

      - name: Upload report_url.txt
        uses: actions/upload-artifact@v4
        with:
          name: ReportUrl
          path: "report_url.txt"
