# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Desktop Tests CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to run against"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - production
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      docker_rebuild:
        description: "Rebuild Docker image"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
      test_cycle:
        description: "Test Cycle"
        required: true
        default: "no_google"
        type: choice
        options:
          - "full"
          - "no-google"

jobs:
  check-secrets:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - name: Checkout CI repo.
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: internet-identity-labs/ci_libs
          ref: main
          path: ci_libs

      - name: Show concurency group
        run: |
          echo "REF: ${{ github.ref }}"
          echo "HEAD_REF: ${{ github.head_ref }}"
          echo "BASE_REF: ${{ github.base_ref }}"
          echo "EVENT_NAME: ${{ github.event_name }}"
          echo "REF_NAME: ${{ github.ref_name }}"
          echo "group: nfid-frontend-tests-docker-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.ref_name, 'main' ) }}-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.event_name, 'push' ) || github.ref_name }}"
          echo "group: nfid-frontend-tests-e2e-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.ref_name, 'main' ) }}-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.event_name, 'push' ) || github.ref_name }}"
          echo "cancel-in-progress: ${{ contains( github.event.inputs.test_cycle, 'no-google' ) || contains( github.event_name, 'pull_request' ) }}"

      - name: Check secrets
        run: |
          source ./ci_libs/CI_LIBS.sh
          JSON='${{ toJSON(env) }}'
          ci_check_secrets "${JSON}"
        env:
          REACT_APP_SENTRY_CONNECTION: ${{secrets.DEV_SENTRY_CONNECTION}}
          URL_AWS_USER_E2E_GOOGLE: ${{secrets.URL_AWS_USER_E2E_GOOGLE}}
          LAMBDA_IDENTITY: ${{secrets.LAMBDA_IDENTITY}}
          USERGEEK_API_KEY: ${{secrets.PROD_USERGEEK_API_KEY}}
          USER_DATA_DIR: ${{secrets.USER_DATA_DIR}}
          PSYCHEDELIC_GH_NPM_REGISTRY: ${{secrets.PSYCHEDELIC_GH_NPM_REGISTRY}}
          ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
          GOERLI_ALCHEMY_API_KEY: ${{secrets.GOERLI_ALCHEMY_API_KEY}}
          RARIBLE_X_API_KEY: ${{secrets.RARIBLE_X_API_KEY}}
          PROD_RARIBLE_X_API_KEY: ${{secrets.PROD_RARIBLE_X_API_KEY}}
          ETH_ALCHEMY_API_KEY: ${{secrets.ETH_ALCHEMY_API_KEY}}
          MATIC_ALCHEMY_API_KEY: ${{secrets.MATIC_ALCHEMY_API_KEY}}
          MUMBAI_ALCHEMY_API_KEY: ${{secrets.MUMBAI_ALCHEMY_API_KEY}}
          BLOCK_CYPHER_TOKEN: ${{secrets.BLOCK_CYPHER_TOKEN_DEV}}

  docker-for-e2e:
    needs: check-secrets
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, Linux, x64, frontend]
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: nfid-test

    concurrency:
      group: nfid-frontend-tests-docker-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.ref_name, 'main' ) }}-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.event_name, 'push' ) || github.ref_name }}
      cancel-in-progress: ${{ contains( github.event.inputs.test_cycle, 'no-google' ) || contains( github.event_name, 'pull_request' ) }}

    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4

      - name: Checkout CI repo.
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: internet-identity-labs/ci_libs
          ref: main
          path: ci_libs

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Pull Build Push Image
        run: |
          source ./ci_libs/CI_LIBS.sh

          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo ${IMAGE_ID} | tr '[A-Z]' '[a-z]')

          # Check is this pull request
          if [ -z "${{ github.head_ref }}" ]; then
            # If NOT
            # Strip git ref prefix from version
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          else
            # If YES
            # Strip git ref prefix from version and left pull-request number
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\([0-9]\+\)/\(.*\),\1-\2,')
          fi

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo ${VERSION} | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "${VERSION}" == "main" ] && VERSION=latest

          # Preparing env Vars
          if [ "${{ github.event.inputs.logLevel }}" == 'debug' ]; then
            CI_DEBUG='true'
          fi

          ci_echo_info "IMAGE_ID: ${IMAGE_ID}" >&2
          ci_echo_info "VERSION : ${VERSION}" >&2

          ci_echo_debug "DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect ${IMAGE_ID}:${VERSION} >/dev/null" >&2
          if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect ${IMAGE_ID}:${VERSION} >/dev/null; then
            ci_echo_info "Docker image '${IMAGE_ID}:${VERSION}' was found" >&2
            DOCKER_REBUILD="false"
          else
            ci_echo_warn "Image '${IMAGE_ID}:${VERSION}' was not found" >&2
            DOCKER_REBUILD="true"
          fi

          if [ "${DOCKER_REBUILD}" == "true" ] || [ "${{ github.event.inputs.docker_rebuild }}" == "true" ]; then
            ci_echo_warn "Will try to build the Docker Image." >&2

            pushd ./docker-e2e-tests

            ci_echo_debug "docker build . \
              --build-arg USER_ID=$(id -u) \
              --build-arg GROUP_ID=$(id -g) \
              --file Dockerfile \
              --tag ${IMAGE_NAME} \
              --label 'runnumber=${GITHUB_RUN_ID}'" >&2

            docker build . \
              --build-arg USER_ID=$(id -u) \
              --build-arg GROUP_ID=$(id -g) \
              --file Dockerfile \
              --tag ${IMAGE_NAME} \
              --label "runnumber=${GITHUB_RUN_ID}"

            ci_echo_debug "docker tag ${IMAGE_NAME} ${IMAGE_ID}:${VERSION}" >&2
            docker tag ${IMAGE_NAME} ${IMAGE_ID}:${VERSION}

            ci_echo_debug "docker push ${IMAGE_ID}:${VERSION}" >&2
            docker push ${IMAGE_ID}:${VERSION}
          fi

  unit-tests:
    needs: check-secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CI repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Build project
        run: |
          cat > ~/.npmrc << EOF
          @psychedelic:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${PSYCHEDELIC_GH_NPM_REGISTRY}
          EOF
          yarn --prefer-offline

        env:
          PSYCHEDELIC_GH_NPM_REGISTRY: ${{secrets.PSYCHEDELIC_GH_NPM_REGISTRY}}
          ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
          GOERLI_ALCHEMY_API_KEY: ${{secrets.GOERLI_ALCHEMY_API_KEY}}
          RARIBLE_X_API_KEY: ${{secrets.RARIBLE_X_API_KEY}}
          PROD_RARIBLE_X_API_KEY: ${{secrets.PROD_RARIBLE_X_API_KEY}}
          ETH_ALCHEMY_API_KEY: ${{secrets.ETH_ALCHEMY_API_KEY}}
          MATIC_ALCHEMY_API_KEY: ${{secrets.MATIC_ALCHEMY_API_KEY}}
          MUMBAI_ALCHEMY_API_KEY: ${{secrets.MUMBAI_ALCHEMY_API_KEY}}
          BLOCK_CYPHER_TOKEN: ${{secrets.BLOCK_CYPHER_TOKEN_DEV}}
          LAMBDA_IDENTITY: ${{secrets.LAMBDA_IDENTITY}}

      - name: Run unit tests
        run: npx env-cmd -f .env.test nx run-many --target=test --skip-nx-cache
        env:
          ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
          GOERLI_ALCHEMY_API_KEY: ${{secrets.GOERLI_ALCHEMY_API_KEY}}
          RARIBLE_X_API_KEY: ${{secrets.RARIBLE_X_API_KEY}}
          PROD_RARIBLE_X_API_KEY: ${{secrets.PROD_RARIBLE_X_API_KEY}}
          ETH_ALCHEMY_API_KEY: ${{secrets.ETH_ALCHEMY_API_KEY}}
          MATIC_ALCHEMY_API_KEY: ${{secrets.MATIC_ALCHEMY_API_KEY}}
          MUMBAI_ALCHEMY_API_KEY: ${{secrets.MUMBAI_ALCHEMY_API_KEY}}
          BLOCK_CYPHER_TOKEN: ${{secrets.BLOCK_CYPHER_TOKEN_DEV}}
          LAMBDA_IDENTITY: ${{secrets.LAMBDA_IDENTITY}}

      - name: Upload build artefacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: yarn-error-logs
          path: /home/runner/work/nfid-frontend/nfid-frontend/yarn-error.log

  e2e-tests:
    needs: docker-for-e2e
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, Linux, x64, frontend]
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: nfid-test
    concurrency:
      group: nfid-frontend-tests-e2e-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.ref_name, 'main' ) }}-${{ contains( github.event.inputs.test_cycle, 'full') || contains( github.event_name, 'push' ) || github.ref_name }}
      cancel-in-progress: ${{ contains( github.event.inputs.test_cycle, 'no-google' ) || contains( github.event_name, 'pull_request' ) }}

    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4

      - name: Checkout CI repo.
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: internet-identity-labs/ci_libs
          ref: main
          path: ci_libs

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Pull Image and preparing Env Vars
        id: pull_image
        run: |
          source ./ci_libs/CI_LIBS.sh

          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo ${IMAGE_ID} | tr '[A-Z]' '[a-z]')

          # Check is this pull request
          if [ -z "${{ github.head_ref }}" ]; then
            # If NOT
            # Strip git ref prefix from version
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          else
            # If YES
            # Strip git ref prefix from version and left pull-request number
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\([0-9]\+\)/\(.*\),\1-\2,')
          fi

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo ${VERSION} | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "${VERSION}" == "main" ] && VERSION=latest

          # Preparing env Vars
          if [ "${{ github.event.inputs.logLevel }}" == 'debug' ]; then
            CI_DEBUG='true'
          fi

          ci_echo_info "IMAGE_ID: ${IMAGE_ID}" >&2
          ci_echo_info "VERSION : ${VERSION}" >&2

          ci_echo_debug "docker pull ${IMAGE_ID}:${VERSION}" >&2
          docker pull ${IMAGE_ID}:${VERSION}

          # Save VARS for next steps
          case "${{ github.event.inputs.test_cycle }}" in
            full)
              TEST_ADD_PARAMS=""
              ;;
            *)
              TEST_ADD_PARAMS="--cucumberOpts.tagExpression='not @only_deploy_to_main and not @pending and not @mobile'"
              ;;
          esac

          # If branch main, run full cycle
          if [ "${{ github.ref_name }}" == 'main' ]; then
            TEST_ADD_PARAMS=""
            CI_DEBUG='true'
          fi

          echo "IMAGE_ID=${IMAGE_ID}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "CI_DEBUG=${CI_DEBUG}" >> $GITHUB_ENV
          echo "TEST_ADD_PARAMS="${TEST_ADD_PARAMS}"" >> $GITHUB_ENV

      - name: Checkout Google user E2E
        uses: actions/checkout@v4
        with:
          repository: internet-identity-labs/user-google-e2e
          path: apps/nfid-frontend-e2e/chrome-user-data-dir
          ref: main
          token: ${{ secrets.PAT }}

      - name: Cache Node Modules.
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/.eslintcache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Run tests
        run: |
          source ./ci_libs/CI_LIBS.sh

          ci_echo_info "Cleaning Allure folders" >&2
          rm -rf apps/nfid-frontend-e2e/allure-results
          rm -rf apps/nfid-frontend-e2e/allure-report
          mkdir -p apps/nfid-frontend-e2e/allure-results
          mkdir -p apps/nfid-frontend-e2e/allure-report

          cat > npmrc_file << EOF
          @psychedelic:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${PSYCHEDELIC_GH_NPM_REGISTRY}
          EOF

          cat > docker_env << EOF
            IS_DEV=true
            IS_E2E_TEST=true
            ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
            GOERLI_ALCHEMY_API_KEY=${GOERLI_ALCHEMY_API_KEY}
            RARIBLE_X_API_KEY=${RARIBLE_X_API_KEY}
            PROD_RARIBLE_X_API_KEY=${PROD_RARIBLE_X_API_KEY}
            ETH_ALCHEMY_API_KEY=${ETH_ALCHEMY_API_KEY}
            MATIC_ALCHEMY_API_KEY=${MATIC_ALCHEMY_API_KEY}
            MUMBAI_ALCHEMY_API_KEY=${MUMBAI_ALCHEMY_API_KEY}
            RAMP_WALLET_API_KEY=${RAMP_WALLET_API_KEY}

            REACT_APP_SENTRY_CONNECTION=${REACT_APP_SENTRY_CONNECTION}
            USERGEEK_API_KEY=${USERGEEK_API_KEY}
            PSYCHEDELIC_GH_NPM_REGISTRY=${PSYCHEDELIC_GH_NPM_REGISTRY}
            BLOCK_CYPHER_TOKEN=${BLOCK_CYPHER_TOKEN}

            URL_AWS_USER_E2E_GOOGLE=${URL_AWS_USER_E2E_GOOGLE}
            LAMBDA_IDENTITY=${LAMBDA_IDENTITY}
          EOF

          ci_echo_debug "docker run --rm \
            -v $(pwd):/home/user/workdir \
            -v $(pwd)/npmrc_file:/home/user/.npmrc \
            --env-file $(pwd)/docker_env \
            -e CI_DEBUG='${CI_DEBUG}' \
            ${IMAGE_ID}:${VERSION} \
            '${TEST_ADD_PARAMS}'" >&2

          docker run --rm \
            -v $(pwd):/home/user/workdir \
            -v $(pwd)/npmrc_file:/home/user/.npmrc \
            --env-file $(pwd)/docker_env \
            -e CI_DEBUG="${CI_DEBUG}" \
            ${IMAGE_ID}:${VERSION} \
            "${TEST_ADD_PARAMS}"
        env:
          IS_DEV: true
          IS_E2E_TEST: true
          ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
          GOERLI_ALCHEMY_API_KEY: ${{secrets.GOERLI_ALCHEMY_API_KEY}}
          RARIBLE_X_API_KEY: ${{secrets.RARIBLE_X_API_KEY}}
          PROD_RARIBLE_X_API_KEY: ${{secrets.PROD_RARIBLE_X_API_KEY}}
          ETH_ALCHEMY_API_KEY: ${{secrets.ETH_ALCHEMY_API_KEY}}
          MATIC_ALCHEMY_API_KEY: ${{secrets.MATIC_ALCHEMY_API_KEY}}
          MUMBAI_ALCHEMY_API_KEY: ${{secrets.MUMBAI_ALCHEMY_API_KEY}}
          RAMP_WALLET_API_KEY: ${{secrets.RAMP_WALLET_API_KEY}}

          REACT_APP_SENTRY_CONNECTION: ${{secrets.DEV_SENTRY_CONNECTION}}
          USERGEEK_API_KEY: ${{secrets.PROD_USERGEEK_API_KEY}}
          PSYCHEDELIC_GH_NPM_REGISTRY: ${{secrets.PSYCHEDELIC_GH_NPM_REGISTRY}}
          BLOCK_CYPHER_TOKEN: ${{secrets.BLOCK_CYPHER_TOKEN_DEV}}

          URL_AWS_USER_E2E_GOOGLE: ${{secrets.URL_AWS_USER_E2E_GOOGLE}}
          LAMBDA_IDENTITY: ${{secrets.LAMBDA_IDENTITY}}

      - name: Caching allure-results
        if: always()
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: apps/nfid-frontend-e2e/allure-results
          key: allure-results-${{github.RUN_ID}}

      - name: Upload Chrome logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: chrome_debug.log
          path: apps/nfid-frontend-e2e/chrome-user-data-dir/chrome_debug.log

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dist
          path: dist

  allure-report:
    needs: e2e-tests
    if: always()
    runs-on: ubuntu-latest
    env:
      URL: ${{ github.event.pull_request.comments_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}
    steps:
      - name: Get Allure history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Working with cache.
        uses: pat-s/always-upload-cache@v3.0.11
        with:
          path: apps/nfid-frontend-e2e/allure-results
          key: allure-results-${{github.RUN_ID}}

      - name: Preparing the report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: apps/nfid-frontend-e2e/allure-results
          gh_pages: gh-pages
          allure_report: apps/nfid-frontend-e2e/allure-report
          allure_history: apps/nfid-frontend-e2e/allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: apps/nfid-frontend-e2e/allure-history

      - name: Upload url to file
        env:
          target_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}
        run: echo "$target_url" > "report_url.txt"

      - name: Upload url to PR comments.
        run: |
          if [ -n "${URL}" ]; then
            printf -v data '{ "body": "%s" }' "$TARGET_URL" &&
            curl \
              -X POST \
              $URL \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "$data"
          fi

      - name: Upload reports.
        uses: actions/upload-artifact@v3
        with:
          name: ReportUrl
          path: "report_url.txt"
